name: chromatic

on:
  pull_request:
    paths:
      - ".github/workflows/chromatic.yml"
      - "src/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "tsconfig.build.json"
      - "tsconfig.json"
      - "tsconfig.node.json"
      - "vite.config.ts"

jobs:
  chromatic:
    runs-on: ubuntu-22.04
    env:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js v19.4.0
        uses: actions/setup-node@v2
        with:
          node-version: 19.4.0

      - name: Set up pnpm v7.26
        uses: pnpm/action-setup@v2
        with:
          version: 7.26
          run_install: false

      - name: Set up node_modules cache
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          key: node-modules-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
          path: '**/node_modules'

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

      - name: Run the Chromatic CI
        run: pnpm run chromatic:ci
