name: linters

on:
  pull_request:
    paths:
      - ".github/workflows/linters.yml"
      - "src/**"
      - ".eslintignore"
      - ".eslintrc.cjs"
      - "package.json"
      - "pnpm-lock.yaml"
      - "tsconfig.json"
      - "tsconfig.node.json"
      - "vite.config.ts"

jobs:
  eslint:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js v19.4.0
        uses: actions/setup-node@v2
        with:
          node-version: 19.4.0

      - name: Set up pnpm v7.26
        uses: pnpm/action-setup@v2
        with:
          version: 7.26
          run_install: false

      - name: Set up node_modules cache
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          key: node-modules-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
          path: '**/node_modules'

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

      - name: Lint with ESLint
        run: pnpm run lint:eslint
