name: release

on:
  push:
    branches:
      - stable

jobs:
  npm-release:
    runs-on: ubuntu-22.04
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js v19.4.0
        uses: actions/setup-node@v2
        with:
          node-version: 19.4.0

      - name: Set up node_modules cache
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          key: node-modules-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
          path: '**/node_modules'

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

      - name: Build Geometr
        run: pnpm run build

      - name: Publish Geometr
        run: pnpm publish

  github-release:
    needs: npm-release

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js v19.4.0
        uses: actions/setup-node@v2
        with:
          node-version: 19.4.0

      - name: Set up node_modules cache
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          key: node-modules-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
          path: '**/node_modules'

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

      - name: Get version
        id: version
        run: echo ::set-output name=version::$(pnpm run --silent version:get)

      - name: Get Pull Request data
        uses: jwalton/gh-find-current-pr@v1
        id: find-pr
        with:
          state: all

      - name: Tag and Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: ${{ steps.version.outputs.version }}
          body: |
            ${{ steps.find-pr.outputs.body }}
          draft: false
          prerelease: false
